### PR TITLE
Add tcl to dependency list

### PR DESCRIPTION
**Pull request by sharkwouter**
It is checked when running and installed by the debian prepare script

### CODE REVIEW

**Comment by carstene1ns** [comment]
I do not think it is really used, but we either should mention it or remove it, right.

**Comment by sharkwouter** [comment]
I just found that tcl is needed to build sqlite in psplibraries.

**Comment by carstene1ns** [comment]
i would rather update sqlite to get rid of it.

From https://www.sqlite.org/tclsqlite.html:
>The SQLite library is designed to be very easy to use from a Tcl or Tcl/Tk script. SQLite began as a Tcl extension and the primary test suite for SQLite is written in TCL. SQLite can be used with any programming language, but its connections to TCL run deep.

**Comment by sharkwouter** [comment]
That's fine too. I'll remove this commit from my other PR and close this one then

**Pull request closed without merging**
