### PR TITLE
Adding gcc 4.9.3 support

### PR DESCRIPTION
**Pull request by davidgfnet**

### CODE REVIEW

**Comment by artart78** [comment]
Very nice! Can you remove the gcc 4.8.5 file? It seems pointless to have it.

**Comment by Fighter19** [comment]
:D I did a patch for 4.8.1  (which I didn't add as a pull request cause I had no idea if I was doing it correctly) But this is even greater!

**Comment by davidgfnet** [comment]
I did a patch for 4.8.something I recall. Have you tested it?
I couldn't fully validate my setup (I mean, some demos work, but my project doesn't) due to some segfaults in libfreetype. I have no idea who to blame, I might take a look at some point.

**Comment by davidgfnet** [comment]
@artart78 should I repost this? I lost track of my repos, could you just cherry pick 9d369b3 and push it? I think it's nice for most people to have 4.9.3 (for C++11 mainly)

**Comment by artart78** [comment]
Done. Thanks!

**Pull request closed without merging**
