### PR TITLE
Add psp-pkg-config

### PR DESCRIPTION
**Pull request by carstene1ns**
This will remove the need for host `pkg-config` and aid in building our libraries without getting fooled by host packages.

### CODE REVIEW

**Comment by sharkwouter** [comment]
Nice! I'll try this out tomorrow

**Comment by sharkwouter** [comment]
Okay, I've finally gotten to testing this. Somehow the toolchain scripts ends when it is done installing pkg-config, even though there are more steps after it. Here is the log:
```
crypto.c:1373:2: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
cc   ebootsign.o crypto.o kirk_engine.o pack-pbp.o unpack-pbp.o fix-realocations.o   -o ebootsign
install ebootsign /home/wouter/Sources/psptoolchain/pspdev/bin
Cloning into 'psp-pkgconf'...
remote: Enumerating objects: 171, done.
remote: Counting objects: 100% (171/171), done.
remote: Compressing objects: 100% (155/155), done.
remote: Total 171 (delta 36), reused 68 (delta 10), pack-reused 0
Receiving objects: 100% (171/171), 129.08 KiB | 1.21 MiB/s, done.
Resolving deltas: 100% (36/36), done.
CC   libpkgconf/argvsplit.c
CC   libpkgconf/audit.c
CC   libpkgconf/bsdstubs.c
CC   libpkgconf/cache.c
CC   libpkgconf/client.c
CC   libpkgconf/dependency.c
CC   libpkgconf/fileio.c
CC   libpkgconf/fragment.c
CC   libpkgconf/parser.c
CC   libpkgconf/path.c
CC   libpkgconf/personality.c
CC   libpkgconf/pkg.c
CC   libpkgconf/queue.c
CC   libpkgconf/tuple.c
CC   cli/getopt_long.c
CC   cli/main.c
CCLD psp-pkg-config
install -Dm755 psp-pkg-config /home/wouter/Sources/psptoolchain/pspdev/bin/psp-pkg-config
install -Dm644 pkg.m4 /home/wouter/Sources/psptoolchain/pspdev/psp/share/aclocal/pkg.m4
wouter@wouter-pc:~/Sources/psptoolchain$ echo $?
0
```
I have the (almost) full log here: https://gist.github.com/sharkwouter/d00aace0bda8cad3db76e584a5cb2198

I was installing using ``./toolchain-local.sh`` as a regular user.

**Comment by carstene1ns** [comment]
Need to update the `seq` here :man_shrugging:
https://github.com/pspdev/psptoolchain/blob/e9e952628a192cc9e29ee338eb8e300fbe95ab40/toolchain-local.sh#L10

**Comment by carstene1ns** [comment]
Actually writing to /etc/profile is bad anyway. So we should change script 12 (now 13) to be informative only.

**Comment by sharkwouter** [comment]
Yeah, I guess it should just be made to run everything for toolchain-local

**Comment by sharkwouter** [comment]
On my system all libraries build fine with this change. I will run it once more in docker and report back

**Comment by sharkwouter** [comment]
It builds fine in docker as well, which there aren't any added dependencies.

**Comment by carstene1ns** [comment]
Should also be able to remove pkg-config from dockers dependencies.

**Comment by sharkwouter** [comment]
I will try that, hopefully I get to it tonight

**Comment by carstene1ns** [comment]
Moving this to https://github.com/pspdev/pspdev.

**Comment by sharkwouter** [comment]
It does build without pkg-config installed. I don't think we can leave out pkg-config as a dependency, though, unless we find a way to build psp-pacman without it.

**Comment by carstene1ns** [comment]
Yep, meson needs it to figure out dependencies for pacman.
Fortunately this vanishes as soon as we have binary releases.

**Comment by sharkwouter** [comment]
Yes, I would say so. I've not had any issues with it when building psp-pkgconf or when installing psplibraries using it.

I'm not that familiar with using pkgconf when developing something, though.

**Pull request merged**
